source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 7.1.0"

gem "pg", "~> 1.5"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

gem "bunny", "~> 2.22"

gem "dotenv-rails", "~> 2.8"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  
  gem "rspec-rails", "~> 6.0"
  
  gem "factory_bot_rails", "~> 6.2"
  
  gem "faker", "~> 3.2"
  
  gem "webmock", "~> 3.19"
end
